
library(ggplot2)

load("./Schlogl_reduced_calibration/Schlogl_reduced-calibration_optim.RData")
load("./Schlogl_reduced_calibration/Schlogl_reduced-calibration.RData")
reference <- as.data.frame(read.csv("Input/reference_data.csv",
                                    header = FALSE,
                                    sep = ""))
calibration_optim_trace <-read.csv("./Schlogl_reduced_calibration/Schlogl_reduced-calibration_optim-config.csv",sep = "")


# Then, we read all the trajectories generated saving them in a list called
# ListTraces. List that will be rewritten as a data frame in order to use ggplot.
# ConfigID represents the initial condition associated to each trajectory,
# which was generated by using the function implemented in the file Functions.R .

listFile<-list.files("./Schlogl_reduced_calibration/",
                     pattern = ".trace")

id.traces<-calibration_optim_trace$id

ListTraces<-lapply(id.traces,
                   function(x){
                     trace.tmp=read.csv(paste0(
                       "./Schlogl_reduced_calibration/Schlogl_reduced-calibration-",
                       x,
                       ".trace"), sep = "")
                     trace.tmp=data.frame(trace.tmp,ID=calibration_optim_trace$distance[which(calibration_optim_trace$id==x)])
                     return(trace.tmp)
                   })

traces <- do.call("rbind", ListTraces)
mid = min(traces$ID) + (max(traces$ID) - min(traces$ID)) / 6

plX1<-ggplot( )+
  geom_line(data=traces,
            aes(x=Time/7,y=X1,group=ID,col=ID))+
  scale_color_gradient2(low="red",mid="white",high="blue",midpoint=mid,limits=c(min(traces$ID),max(traces$ID)))+
  geom_line(data=reference,
            aes(x=V1/7,y=V2),
            col="red")+
  theme(axis.text=element_text(size=18),
        axis.title=element_text(size=20,face="bold"),
        legend.text=element_text(size=18),
        legend.title=element_text(size=20,face="bold"),
        legend.position="right",
        legend.key.size = unit(1.3, "cm"),
        legend.key.width = unit(1.3,"cm") )+
  labs(x="Time", y="X1",col="Distance")
plX1
